name       : perl-font-ttf
version    : 1.06
release    : 4
source     :
    - http://search.cpan.org/CPAN/authors/id/B/BH/BHALLISSY/Font-TTF-1.06.tar.gz : 4b697d444259759ea02d2c442c9bffe5ffe14c9214084a01f743693a944cc293
license    : Artistic-2.0
component  : programming.perl
summary    : Perl module for TrueType/OpenType font hacking.
description: |
    Perl module for TrueType/OpenType font hacking. Supports reading, processing and writing of the following tables: GDEF, GPOS, GSUB, LTSH, OS/2, PCLT, bsln, cmap, cvt, fdsc, feat, fpgm, glyf, hdmx, head, hhea, hmtx, kern, loca, maxp, mort, name, post, prep, prop, vhea, vmtx and the reading and writing of all other table types.
builddeps  :
    - perl-io-string
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
